### ISSUE TITLE
Gateways

### ISSUE THREAD

**Issue by billythekid** [ethercreative/web-payments#14]
Hi all,

I've been trying out this plugin for a client and I have a few questions.

How likely is it that this plugin will be developed to be able to pass payments through to other gateways? I know that as developers we love Stripe but when a client has an existing vendor in place to accept their card payments we're kind of stuck with that. Would it be possible for a developer to create some sort of 'bridging' plugins betwen web payments plugin and gatewayX and if so what technical challenges would they face? What happens behind the scenes here?

I see that Stripe makes it super easy to hook in to apple pay as you only need to add the 'verified' file to your site and your URL at stripe and it's taken care of. I imagine that takes a lot of headache out of the process but is that *all* that's stopping other gateway support? What are the technical difficulties that are faced by a developer with passing payments on to other gateways (or implementing their own web payments system)?

Would be great to read up any blog post or whatever on the development path of the web payments plugins and the technical challenges you faced building it if you have one.

Cheers
Billy

**Comment by alexjcollins** [comment]
Hey Billy,

Thanks for the note!

I'd say it's reasonably likely, and it has always been something we've been interested in doing. With that in mind, two main factors are likely to drive the speed at which we make those changes;

1. If one of our clients require a particular gateway we will build support (they would foot the bill!), or
2. If there's enough community appetite for supporting a specific gateway 

In terms of point 2, we would also have to consider international support; for example, two front-runners early on were Worldpay and Braintree as they have good international support, as opposed to something like Square, which only has support in the USA. 

Ideally, any work we do on extending the gateways needs to make financial sense to us, which is why point 1 is probably the most likely way a gateway will be added. To add some context, the plugin, despite having 309 'installs,' has translated to only five people buying the plugin!

Finally, looking at the work involved, I don't think it's all that significant (I'm not a technical person), but it does still very much depend on the gateway and how it supports the protocol. 
The plan, like it currently is with Stripe, would be to bridge an existing Gateway plugin to support Web Payments. So if we started supporting Worldpay, we'd require the [Worldpay gateway](https://plugins.craftcms.com/commerce-worldpay).

We don't currently have a write-up or blog post on the plugin and the work, but I think it would make for a fascinating read.

I hope that helps answer your questions and I'm happy to answer more if you have any.

Cheers

Alex

**Comment by billythekid** [comment]
Cheers Alex,

Yeah I get the problem, no point making it if there's no demand unless it suits your needs. 

My client is using SagePay for their credit card gateway and was asking about accepting web payments but I've had trouble finding more information on SagePay's docs around support. Figured I'd see if you guys had some insight into generic support but it seems like bridging the gateways will be the answer.

Thanks for the help will relay it all back.

**Comment by alexjcollins** [comment]
I'm not sure if Sage Pay does, at least according to Apple they don't. [This is a super-handy page](https://developer.apple.com/apple-pay/payment-platforms/) for checking out which gateways support Apple Pay. 
You can hit `Payment Service Providers` and then select the country. 

It might be that they offer Apple Pay through PDQ machines, but not through the web.

**Comment by billythekid** [comment]
Oh that's excellent, cheers! Yeah SagePay do offer payment via terminals so might be that. Thanks again, that's super helpful!
